# Settings for Bolt Article

# All options: blockcode, buttonlink, definedlinks, handle, inlineformat, icons, specialchars, reorder, print, selector, style, tags, underline, variable
default:
  plugins: [ blockcode, buttonlink, definedlinks, inlineformat, reorder, underline, style, icons, specialchars, print, selector, imageposition]
  source: true
  custom:
    css: ['/theme/oc-aventures-2021/css/tailwind.css', '/theme/oc-aventures-2021/css/base-2021.css']

  styles:      
      text:
        'lead':
          title: '<span style="font-size: 1rem; color: #363636;font-family: inhertit; font-weight: 700;">STYLE IMPORTANT</span>'
          classname: 'font-bold uppercase'
        'normal-block':
          title: '<span style="font-size: 1rem; color: #363636;background-color: #EDDEAB;font-family: inhertit, sans-serif;">Style Normal</span>'
          classname: 'text-sombre text-base bg-sable font-sans'
        'red-block':
          title: '<span style="font-size: 1rem; background-color: #87200C;font-family: inhertit, sans-serif;color: #EDDEAB; padding: 4px; border-radius:3px;">Fond Rose</span>'
          classname: 'text-sable bg-rouge text-base font-sans'
        'blue-block':
          title: '<span style="font-size: 1rem; background-color: #9ED8B0;color: #363636;font-family: inhertit, sans-serif; padding: 4px; border-radius:3px;">Fond Bleu</span>'
          classname: 'text-sombre bg-vert-ciel text-base font-sans'
      
      heading:
        'h-normal-block':
          title: '<span style="font-size: 1rem; color: #363636;background-color: #EDDEAB;font-family: inhertit, sans-serif;">Style Normal</span>'
          classname: 'text-sombre text-base bg-sable font-sans'
        'h-red-block':
          title: '<span style="font-size: 1rem; background-color: #87200C;font-family: inhertit, sans-serif;color: #EDDEAB; padding: 4px; border-radius:3px;">Fond Rose</span>'
          classname: 'text-white bg-pink text-base font-sans'
        'h-blue-block':
          title: '<span style="font-size: 1rem; background-color: #9ED8B0;color: #363636;font-family: inhertit, sans-serif; padding: 4px; border-radius:3px;">Fond Bleu</span>'
          classname: 'text-sombre bg-vert-ciel text-base font-sans'
      
      layer:
        'section-base':
          title: '<span style="font-size: 1rem; color: #363636;background-color: #EDDEAB;font-family: inhertit, sans-serif;">Style Normal</span>'
          classname: 'text-sombre text-base bg-sable font-sans'
        'section-red':
          title: '<span style="font-size: 1rem; background-color: #87200C;font-family: inhertit, sans-serif;color: #EDDEAB; padding: 4px; border-radius:3px;">Fond Rose</span>'
          classname: 'text-white bg-pink text-base font-sans'
        'section-blue':
          title: '<span style="font-size: 1rem; background-color: #9ED8B0;color: #363636;font-family: inhertit, sans-serif; padding: 4px; border-radius:3px;">Fond Bleu</span>'
          classname: 'text-sombre bg-vert-ciel text-base font-sans'
  
  icons:
    items: [ ğŸ˜€, ğŸ˜ƒ, ğŸ˜„, ğŸ˜, ğŸ˜†, ğŸ˜…, ğŸ˜‚, ğŸ¤£, ğŸ˜Š, ğŸ˜‡, ğŸ™‚, ğŸ™ƒ, ğŸ˜‰, ğŸ˜Œ, ğŸ˜, ğŸ¥°, ğŸ˜˜, ğŸ˜—, ğŸ˜™, ğŸ˜š, ğŸ˜‹, ğŸ˜›, ğŸ˜, ğŸ˜œ, ğŸ¤ª, ğŸ¤¨, ğŸ§, ğŸ¤“, ğŸ˜, ğŸ¤©, ğŸ¥³, ğŸ˜, ğŸ˜’, ğŸ˜, ğŸ˜”, ğŸ˜Ÿ, ğŸ˜•, ğŸ™, ğŸ˜£, ğŸ˜–, ğŸ˜«, ğŸ˜©, ğŸ¥º, ğŸ˜¢, ğŸ˜­, ğŸ˜¤, ğŸ˜ , ğŸ˜¡, ğŸ¤¬, ğŸ¤¯, ğŸ˜³, ğŸ¥µ, ğŸ¥¶, ğŸ˜±, ğŸ˜¨, ğŸ˜°, ğŸ˜¥, ğŸ˜“, ğŸ¤—, ğŸ¤”, ğŸ¤­, ğŸ¤«, ğŸ¤¥, ğŸ˜¶, ğŸ˜, ğŸ˜‘, ğŸ˜¬, ğŸ™„, ğŸ˜¯, ğŸ˜¦, ğŸ˜§, ğŸ˜®, ğŸ˜², ğŸ¥±, ğŸ˜´, ğŸ¤¤, ğŸ˜ª, ğŸ˜µ, ğŸ¤, ğŸ¥´, ğŸ¤¢, ğŸ¤®, ğŸ¤§, ğŸ˜·, ğŸ¤’, ğŸ¤•, ğŸ¤‘, ğŸ¤ , ğŸ˜ˆ, ğŸ‘¿, ğŸ‘¹, ğŸ‘º, ğŸ¤¡, ğŸ’©, ğŸ‘», ğŸ’€, â˜ ï¸, ğŸ‘½, ğŸ‘¾, ğŸ¤–, ğŸƒ, ğŸ˜º, ğŸ˜¸, ğŸ˜¹, ğŸ˜», ğŸ˜¼, ğŸ˜½, ğŸ™€, ğŸ˜¿, ğŸ˜¾,
    ğŸ‘‹, ğŸ¤š, ğŸ–, âœ‹, ğŸ––, ğŸ‘Œ, ğŸ¤, ğŸ¤, ğŸ¤Ÿ, ğŸ¤˜, ğŸ¤™, ğŸ‘ˆ, ğŸ‘‰, ğŸ‘†, ğŸ–•, ğŸ‘‡, ğŸ‘, ğŸ‘, âœŠ, ğŸ‘Š, ğŸ¤›, ğŸ¤œ, ğŸ‘, ğŸ™Œ, ğŸ‘, ğŸ¤², ğŸ¤, ğŸ™, âœï¸, ğŸ’…, ğŸ¤³, ğŸ’ª, ğŸ¦¾, ğŸ¦µ, ğŸ¦¿, ğŸ¦¶, ğŸ‘£, ğŸ‘‚, ğŸ¦», ğŸ‘ƒ, ğŸ§ , ğŸ¦·, ğŸ¦´, ğŸ‘€, ğŸ‘, ğŸ‘…, ğŸ‘„, ğŸ’‹, ğŸ©¸,
    ğŸ¶, ğŸ±, ğŸ­, ğŸ¹, ğŸ°, ğŸ¦Š, ğŸ», ğŸ¼, ğŸ»â€â„ï¸, ğŸ¨, ğŸ¯, ğŸ¦, ğŸ®, ğŸ·, ğŸ½, ğŸ¸, ğŸµ, ğŸ™ˆ, ğŸ™‰, ğŸ™Š, ğŸ’, ğŸ”, ğŸ§, ğŸ¦, ğŸ¤, ğŸ£, ğŸ¥, ğŸ¦†, ğŸ¦…, ğŸ¦‰, ğŸ¦‡, ğŸº, ğŸ—, ğŸ´, ğŸ¦„, ğŸ, ğŸ›, ğŸ¦‹, ğŸŒ, ğŸ, ğŸœ, ğŸ¦Ÿ, ğŸ¦—, ğŸ•·, ğŸ•¸, ğŸ¦‚, ğŸ¢, ğŸ, ğŸ¦, ğŸ¦–, ğŸ¦•, ğŸ™, ğŸ¦‘, ğŸ¦, ğŸ¦, ğŸ¦€, ğŸ¡, ğŸ , ğŸŸ, ğŸ¬, ğŸ³, ğŸ‹, ğŸ¦ˆ, ğŸŠ, ğŸ…, ğŸ†, ğŸ¦“, ğŸ¦, ğŸ¦§, ğŸ˜, ğŸ¦›, ğŸ¦, ğŸª, ğŸ«, ğŸ¦’, ğŸ¦˜, ğŸƒ, ğŸ‚, ğŸ„, ğŸ, ğŸ–, ğŸ, ğŸ‘, ğŸ¦™, ğŸ, ğŸ¦Œ, ğŸ•, ğŸ©, ğŸ¦®, ğŸ•â€ğŸ¦º, ğŸˆ, ğŸˆâ€, ğŸ“, ğŸ¦ƒ, ğŸ¦š, ğŸ¦œ, ğŸ¦¢, ğŸ¦©, ğŸ•Š, ğŸ‡, ğŸ¦, ğŸ¦¨, ğŸ¦¡, ğŸ¦¦, ğŸ¦¥, ğŸ, ğŸ€, ğŸ¿, ğŸ¦”, ğŸ¾, ğŸ‰, ğŸ², ğŸŒµ, ğŸ„, ğŸŒ², ğŸŒ³, ğŸŒ´, ğŸŒ±, ğŸŒ¿, â˜˜ï¸, ğŸ€, ğŸ, ğŸ‹, ğŸƒ, ğŸ‚, ğŸ, ğŸ„, ğŸš, ğŸŒ¾, ğŸ’, ğŸŒ·, ğŸŒ¹, ğŸ¥€, ğŸŒº, ğŸŒ¸, ğŸŒ¼, ğŸŒ», ğŸŒ, ğŸŒ, ğŸŒ›, ğŸŒœ, ğŸŒš, ğŸŒ•, ğŸŒ–, ğŸŒ—, ğŸŒ˜, ğŸŒ‘, ğŸŒ’, ğŸŒ“, ğŸŒ”, ğŸŒ™, ğŸŒ, ğŸŒ, ğŸŒ, ğŸª, ğŸ’«, â­ï¸, ğŸŒŸ, âœ¨, âš¡ï¸, â˜„ï¸, ğŸ’¥, ğŸ”¥, ğŸŒª, ğŸŒˆ, â˜€ï¸, ğŸŒ¤, â›…ï¸, ğŸŒ¥, â˜ï¸, ğŸŒ¦, ğŸŒ§, â›ˆ, ğŸŒ©, ğŸŒ¨, â„ï¸, â˜ƒï¸, â›„ï¸, ğŸŒ¬, ğŸ’¨, ğŸ’§, ğŸ’¦, â˜”ï¸, â˜‚ï¸, ğŸŒŠ, ğŸŒ«,
    ğŸ, ğŸ, ğŸ, ğŸŠ, ğŸ‹, ğŸŒ, ğŸ‰, ğŸ‡, ğŸ“, ğŸˆ, ğŸ’, ğŸ‘, ğŸ¥­, ğŸ, ğŸ¥¥, ğŸ¥, ğŸ…, ğŸ†, ğŸ¥‘, ğŸ¥¦, ğŸ¥¬, ğŸ¥’, ğŸŒ½, ğŸ¥•, ğŸ§„, ğŸ§…, ğŸ¥”, ğŸ , ğŸ¥, ğŸ¥¯, ğŸ, ğŸ¥–, ğŸ¥¨, ğŸ§€, ğŸ¥š, ğŸ³, ğŸ§ˆ, ğŸ¥, ğŸ§‡, ğŸ¥“, ğŸ¥©, ğŸ—, ğŸ–, ğŸ¦´, ğŸŒ­, ğŸ”, ğŸŸ, ğŸ•, ğŸ¥ª, ğŸ¥™, ğŸ§†, ğŸŒ®, ğŸŒ¯, ğŸ¥—, ğŸ¥˜, ğŸ¥«, ğŸ, ğŸœ, ğŸ², ğŸ›, ğŸ£, ğŸ±, ğŸ¥Ÿ, ğŸ¦ª, ğŸ¤, ğŸ™, ğŸš, ğŸ˜, ğŸ¥, ğŸ¥ , ğŸ¥®, ğŸ¢, ğŸ¡, ğŸ§, ğŸ¨, ğŸ¦, ğŸ¥§, ğŸ§, ğŸ°, ğŸ‚, ğŸ®, ğŸ­, ğŸ¬, ğŸ«, ğŸ¿, ğŸ©, ğŸª, ğŸŒ°, ğŸ¥œ, ğŸ¯, ğŸ¥›, ğŸ¼, â˜•ï¸, ğŸµ, ğŸ§ƒ, ğŸ¥¤, ğŸ¶, ğŸº, ğŸ», ğŸ¥‚, ğŸ·, ğŸ¥ƒ, ğŸ¸, ğŸ¹, ğŸ§‰, ğŸ¾, ğŸ§Š, ğŸ¥„, ğŸ´, ğŸ½, ğŸ¥£, ğŸ¥¡, ğŸ¥¢, ğŸ§‚,
    âš½ï¸, ğŸ€, ğŸˆ, âš¾ï¸, ğŸ¥, ğŸ¾, ğŸ, ğŸ‰, ğŸ¥, ğŸ±, ğŸª€, ğŸ“, ğŸ¸, ğŸ’, ğŸ‘, ğŸ¥, ğŸ, ğŸ¥…, â›³ï¸, ğŸª, ğŸ¹, ğŸ£, ğŸ¤¿, ğŸ¥Š, ğŸ¥‹, ğŸ½, ğŸ›¹, ğŸ›·, â›¸, ğŸ¥Œ, ğŸ¿, â›·, ğŸ‚, ğŸª‚, ğŸ‹ï¸â€â™€ï¸, ğŸ‹ï¸, ğŸ‹ï¸â€â™‚ï¸, ğŸ¤¼â€â™€ï¸, ğŸ¤¼, ğŸ¤¼â€â™‚ï¸, ğŸ¤¸â€â™€ï¸, ğŸ¤¸, ğŸ¤¸â€â™‚ï¸, â›¹ï¸â€â™€ï¸, â›¹ï¸, â›¹ï¸â€â™‚ï¸, ğŸ¤º, ğŸ¤¾â€â™€ï¸, ğŸ¤¾, ğŸ¤¾â€â™‚ï¸, ğŸŒï¸â€â™€ï¸, ğŸŒï¸, ğŸŒï¸â€â™‚ï¸, ğŸ‡, ğŸ§˜â€â™€ï¸, ğŸ§˜, ğŸ§˜â€â™‚ï¸, ğŸ„â€â™€ï¸, ğŸ„, ğŸ„â€â™‚ï¸, ğŸŠâ€â™€ï¸, ğŸŠ, ğŸŠâ€â™‚ï¸, ğŸ¤½â€â™€ï¸, ğŸ¤½, ğŸ¤½â€â™‚ï¸, ğŸš£â€â™€ï¸, ğŸš£, ğŸš£â€â™‚ï¸, ğŸ§—â€â™€ï¸, ğŸ§—, ğŸ§—â€â™‚ï¸, ğŸšµâ€â™€ï¸, ğŸšµ, ğŸšµâ€â™‚ï¸, ğŸš´â€â™€ï¸, ğŸš´, ğŸš´â€â™‚ï¸, ğŸ†, ğŸ¥‡, ğŸ¥ˆ, ğŸ¥‰, ğŸ…, ğŸ–, ğŸµ, ğŸ—, ğŸ«, ğŸŸ, ğŸª, ğŸ¤¹, ğŸ¤¹â€â™‚ï¸, ğŸ¤¹â€â™€ï¸, ğŸ­, ğŸ©°, ğŸ¨, ğŸ¬, ğŸ¤, ğŸ§, ğŸ¼, ğŸ¹, ğŸ¥, ğŸ·, ğŸº, ğŸ¸, ğŸª•, ğŸ», ğŸ², â™Ÿ, ğŸ¯, ğŸ³, ğŸ®, ğŸ°, ğŸ§©,
    ğŸš—, ğŸš•, ğŸš™, ğŸšŒ, ğŸš, ğŸ, ğŸš“, ğŸš‘, ğŸš’, ğŸš, ğŸšš, ğŸš›, ğŸšœ, ğŸ¦¯, ğŸ¦½, ğŸ¦¼, ğŸ›´, ğŸš², ğŸ›µ, ğŸ, ğŸ›º, ğŸš¨, ğŸš”, ğŸš, ğŸš˜, ğŸš–, ğŸš¡, ğŸš , ğŸšŸ, ğŸšƒ, ğŸš‹, ğŸš, ğŸš, ğŸš„, ğŸš…, ğŸšˆ, ğŸš‚, ğŸš†, ğŸš‡, ğŸšŠ, ğŸš‰, âœˆï¸, ğŸ›«, ğŸ›¬, ğŸ›©, ğŸ’º, ğŸ›°, ğŸš€, ğŸ›¸, ğŸš, ğŸ›¶, â›µï¸, ğŸš¤, ğŸ›¥, ğŸ›³, â›´, ğŸš¢, âš“ï¸, â›½ï¸, ğŸš§, ğŸš¦, ğŸš¥, ğŸš, ğŸ—º, ğŸ—¿, ğŸ—½, ğŸ—¼, ğŸ°, ğŸ¯, ğŸŸ, ğŸ¡, ğŸ¢, ğŸ , â›²ï¸, â›±, ğŸ–, ğŸ, ğŸœ, ğŸŒ‹, â›°, ğŸ”, ğŸ—», ğŸ•, â›ºï¸, ğŸ , ğŸ¡, ğŸ˜, ğŸš, ğŸ—, ğŸ­, ğŸ¢, ğŸ¬, ğŸ£, ğŸ¤, ğŸ¥, ğŸ¦, ğŸ¨, ğŸª, ğŸ«, ğŸ©, ğŸ’’, ğŸ›, â›ªï¸, ğŸ•Œ, ğŸ•, ğŸ›•, ğŸ•‹, â›©, ğŸ›¤, ğŸ›£, ğŸ—¾, ğŸ‘, ğŸ, ğŸŒ…, ğŸŒ„, ğŸŒ , ğŸ‡, ğŸ†, ğŸŒ‡, ğŸŒ†, ğŸ™, ğŸŒƒ, ğŸŒŒ, ğŸŒ‰, ğŸŒ,
    âŒšï¸, ğŸ“±, ğŸ“², ğŸ’», âŒ¨ï¸, ğŸ–¥, ğŸ–¨, ğŸ–±, ğŸ–², ğŸ•¹, ğŸ—œ, ğŸ’½, ğŸ’¾, ğŸ’¿, ğŸ“€, ğŸ“¼, ğŸ“·, ğŸ“¸, ğŸ“¹, ğŸ¥, ğŸ“½, ğŸ, ğŸ“, â˜ï¸, ğŸ“Ÿ, ğŸ“ , ğŸ“º, ğŸ“», ğŸ™, ğŸš, ğŸ›, ğŸ§­, â±, â², â°, ğŸ•°, âŒ›ï¸, â³, ğŸ“¡, ğŸ”‹, ğŸ”Œ, ğŸ’¡, ğŸ”¦, ğŸ•¯, ğŸª”, ğŸ§¯, ğŸ›¢, ğŸ’¸, ğŸ’µ, ğŸ’´, ğŸ’¶, ğŸ’·, ğŸ’°, ğŸ’³, ğŸ’, âš–ï¸, ğŸ§°, ğŸ”§, ğŸ”¨, âš’, ğŸ› , â›, ğŸ”©, âš™ï¸, ğŸ§±, â›“, ğŸ§², ğŸ”«, ğŸ’£, ğŸ§¨, ğŸª“, ğŸ”ª, ğŸ—¡, âš”ï¸, ğŸ›¡, ğŸš¬, âš°ï¸, âš±ï¸, ğŸº, ğŸ”®, ğŸ“¿, ğŸ§¿, ğŸ’ˆ, âš—ï¸, ğŸ”­, ğŸ”¬, ğŸ•³, ğŸ©¹, ğŸ©º, ğŸ’Š, ğŸ’‰, ğŸ©¸, ğŸ§¬, ğŸ¦ , ğŸ§«, ğŸ§ª, ğŸŒ¡, ğŸ§¹, ğŸª , ğŸ§º, ğŸ§», ğŸš½, ğŸš°, ğŸš¿, ğŸ›, ğŸ›€, ğŸ§¼, ğŸª¥, ğŸª’, ğŸ§½, ğŸª£, ğŸ§´, ğŸ›, ğŸ”‘, ğŸ—, ğŸšª, ğŸª‘, ğŸ›‹, ğŸ›, ğŸ›Œ, ğŸ§¸, ğŸ›’, ğŸ, ğŸˆ, ğŸ, ğŸ€, ğŸ‰, ğŸ, ğŸ®, ğŸ, ğŸ§§, âœ‰ï¸, ğŸ“©, ğŸ“¨, ğŸ“§, ğŸ’Œ, ğŸ“¥, ğŸ“¤, ğŸ“¦, ğŸ·, ğŸª§, ğŸ“ª, ğŸ“«, ğŸ“¬, ğŸ“­, ğŸ“®, ğŸ“¯, ğŸ“œ, ğŸ“ƒ, ğŸ“„, ğŸ“‘, ğŸ§¾, ğŸ“Š, ğŸ“ˆ, ğŸ“‰, ğŸ—’, ğŸ—“, ğŸ“†, ğŸ“…, ğŸ—‘, ğŸ“‡, ğŸ—ƒ, ğŸ—³, ğŸ—„, ğŸ“‹, ğŸ“, ğŸ“‚, ğŸ—‚, ğŸ—, ğŸ“°, ğŸ““, ğŸ“”, ğŸ“’, ğŸ“•, ğŸ“—, ğŸ“˜, ğŸ“™, ğŸ“š, ğŸ“–, ğŸ”–, ğŸ§·, ğŸ”—, ğŸ“, ğŸ–‡, ğŸ“, ğŸ“, ğŸ§®, ğŸ“Œ, ğŸ“, âœ‚ï¸, ğŸ–Š, ğŸ–‹, âœ’ï¸, ğŸ–Œ, ğŸ–, ğŸ“, âœï¸, ğŸ”, ğŸ”, ğŸ”, ğŸ”, ğŸ”’, ğŸ”“,  
    ğŸ³ï¸,ğŸ´,ğŸ,ğŸš©,ğŸ³ï¸â€ğŸŒˆ,ğŸ³ï¸â€âš§ï¸,ğŸ´â€â˜ ï¸,ğŸ‡¦ğŸ‡«,ğŸ‡¦ğŸ‡½,ğŸ‡¦ğŸ‡±,ğŸ‡©ğŸ‡¿,ğŸ‡¦ğŸ‡¸,ğŸ‡¦ğŸ‡©,ğŸ‡¦ğŸ‡´,ğŸ‡¦ğŸ‡®,ğŸ‡¦ğŸ‡¶,ğŸ‡¦ğŸ‡¬,ğŸ‡¦ğŸ‡·,ğŸ‡¦ğŸ‡²,ğŸ‡¦ğŸ‡¼,ğŸ‡¦ğŸ‡º,ğŸ‡¦ğŸ‡¹,ğŸ‡¦ğŸ‡¿,ğŸ‡§ğŸ‡¸,ğŸ‡§ğŸ‡­,ğŸ‡§ğŸ‡©,ğŸ‡§ğŸ‡§,ğŸ‡§ğŸ‡¾,ğŸ‡§ğŸ‡ª,ğŸ‡§ğŸ‡¿,ğŸ‡§ğŸ‡¯,ğŸ‡§ğŸ‡²,ğŸ‡§ğŸ‡¹,ğŸ‡§ğŸ‡´,ğŸ‡§ğŸ‡¦,ğŸ‡§ğŸ‡¼,ğŸ‡§ğŸ‡·,ğŸ‡®ğŸ‡´,ğŸ‡»ğŸ‡¬,ğŸ‡§ğŸ‡³,ğŸ‡§ğŸ‡¬,ğŸ‡§ğŸ‡«,ğŸ‡§ğŸ‡®,ğŸ‡°ğŸ‡­,ğŸ‡¨ğŸ‡²,ğŸ‡¨ğŸ‡¦,ğŸ‡®ğŸ‡¨,ğŸ‡¨ğŸ‡»,ğŸ‡§ğŸ‡¶,ğŸ‡°ğŸ‡¾,ğŸ‡¨ğŸ‡«,ğŸ‡¹ğŸ‡©,ğŸ‡¨ğŸ‡±,ğŸ‡¨ğŸ‡³,ğŸ‡¨ğŸ‡½,ğŸ‡¨ğŸ‡¨,ğŸ‡¨ğŸ‡´,ğŸ‡°ğŸ‡²,ğŸ‡¨ğŸ‡¬,ğŸ‡¨ğŸ‡©,ğŸ‡¨ğŸ‡°,ğŸ‡¨ğŸ‡·,ğŸ‡¨ğŸ‡®,ğŸ‡­ğŸ‡·,ğŸ‡¨ğŸ‡º,ğŸ‡¨ğŸ‡¼,ğŸ‡¨ğŸ‡¾,ğŸ‡¨ğŸ‡¿,ğŸ‡©ğŸ‡°,ğŸ‡©ğŸ‡¯,ğŸ‡©ğŸ‡²,ğŸ‡©ğŸ‡´,ğŸ‡ªğŸ‡¨,ğŸ‡ªğŸ‡¬,ğŸ‡¸ğŸ‡»,ğŸ‡¬ğŸ‡¶,ğŸ‡ªğŸ‡·,ğŸ‡ªğŸ‡ª,ğŸ‡ªğŸ‡¹,ğŸ‡ªğŸ‡º,ğŸ‡«ğŸ‡°,ğŸ‡«ğŸ‡´,ğŸ‡«ğŸ‡¯,ğŸ‡«ğŸ‡®,ğŸ‡«ğŸ‡·,ğŸ‡¬ğŸ‡«,ğŸ‡µğŸ‡«,ğŸ‡¹ğŸ‡«,ğŸ‡¬ğŸ‡¦,ğŸ‡¬ğŸ‡²,ğŸ‡¬ğŸ‡ª,ğŸ‡©ğŸ‡ª,ğŸ‡¬ğŸ‡­,ğŸ‡¬ğŸ‡®,ğŸ‡¬ğŸ‡·,ğŸ‡¬ğŸ‡±,ğŸ‡¬ğŸ‡©,ğŸ‡¬ğŸ‡µ,ğŸ‡¬ğŸ‡º,ğŸ‡¬ğŸ‡¹,ğŸ‡¬ğŸ‡¬,ğŸ‡¬ğŸ‡³,ğŸ‡¬ğŸ‡¼,ğŸ‡¬ğŸ‡¾,ğŸ‡­ğŸ‡¹,ğŸ‡­ğŸ‡³,ğŸ‡­ğŸ‡°,ğŸ‡­ğŸ‡º,ğŸ‡®ğŸ‡¸,ğŸ‡®ğŸ‡³,ğŸ‡®ğŸ‡©,ğŸ‡®ğŸ‡·,ğŸ‡®ğŸ‡¶,ğŸ‡®ğŸ‡ª,ğŸ‡®ğŸ‡²,ğŸ‡®ğŸ‡±,ğŸ‡®ğŸ‡¹,ğŸ‡¯ğŸ‡²,ğŸ‡¯ğŸ‡µ,ğŸŒ,ğŸ‡¯ğŸ‡ª,ğŸ‡¯ğŸ‡´,ğŸ‡°ğŸ‡¿,ğŸ‡°ğŸ‡ª,ğŸ‡°ğŸ‡®,ğŸ‡½ğŸ‡°,ğŸ‡°ğŸ‡¼,ğŸ‡°ğŸ‡¬,ğŸ‡±ğŸ‡¦,ğŸ‡±ğŸ‡»,ğŸ‡±ğŸ‡§,ğŸ‡±ğŸ‡¸,ğŸ‡±ğŸ‡·,ğŸ‡±ğŸ‡¾,ğŸ‡±ğŸ‡®,ğŸ‡±ğŸ‡¹,ğŸ‡±ğŸ‡º,ğŸ‡²ğŸ‡´,ğŸ‡²ğŸ‡°,ğŸ‡²ğŸ‡¬,ğŸ‡²ğŸ‡¼,ğŸ‡²ğŸ‡¾,ğŸ‡²ğŸ‡»,ğŸ‡²ğŸ‡±,ğŸ‡²ğŸ‡¹,ğŸ‡²ğŸ‡­,ğŸ‡²ğŸ‡¶,ğŸ‡²ğŸ‡·,ğŸ‡²ğŸ‡º,ğŸ‡¾ğŸ‡¹,ğŸ‡²ğŸ‡½,ğŸ‡«ğŸ‡²,ğŸ‡²ğŸ‡©,ğŸ‡²ğŸ‡¨,ğŸ‡²ğŸ‡³,ğŸ‡²ğŸ‡ª,ğŸ‡²ğŸ‡¸,ğŸ‡²ğŸ‡¦,ğŸ‡²ğŸ‡¿,ğŸ‡²ğŸ‡²,ğŸ‡³ğŸ‡¦,ğŸ‡³ğŸ‡·,ğŸ‡³ğŸ‡µ,ğŸ‡³ğŸ‡±,ğŸ‡³ğŸ‡¨,ğŸ‡³ğŸ‡¿,ğŸ‡³ğŸ‡®,ğŸ‡³ğŸ‡ª,ğŸ‡³ğŸ‡¬,ğŸ‡³ğŸ‡º,ğŸ‡³ğŸ‡«,ğŸ‡°ğŸ‡µ,ğŸ‡²ğŸ‡µ,ğŸ‡³ğŸ‡´,ğŸ‡´ğŸ‡²,ğŸ‡µğŸ‡°,ğŸ‡µğŸ‡¼,ğŸ‡µğŸ‡¸,ğŸ‡µğŸ‡¦,ğŸ‡µğŸ‡¬,ğŸ‡µğŸ‡¾,ğŸ‡µğŸ‡ª,ğŸ‡µğŸ‡­,ğŸ‡µğŸ‡³,ğŸ‡µğŸ‡±,ğŸ‡µğŸ‡¹,ğŸ‡µğŸ‡·,ğŸ‡¶ğŸ‡¦,ğŸ‡·ğŸ‡ª,ğŸ‡·ğŸ‡´,ğŸ‡·ğŸ‡º,ğŸ‡·ğŸ‡¼,ğŸ‡¼ğŸ‡¸,ğŸ‡¸ğŸ‡²,ğŸ‡¸ğŸ‡¦,ğŸ‡¸ğŸ‡³,ğŸ‡·ğŸ‡¸,ğŸ‡¸ğŸ‡¨,ğŸ‡¸ğŸ‡±,ğŸ‡¸ğŸ‡¬,ğŸ‡¸ğŸ‡½,ğŸ‡¸ğŸ‡°,ğŸ‡¸ğŸ‡®,ğŸ‡¬ğŸ‡¸,ğŸ‡¸ğŸ‡§,ğŸ‡¸ğŸ‡´,ğŸ‡¿ğŸ‡¦,ğŸ‡°ğŸ‡·,ğŸ‡¸ğŸ‡¸,ğŸ‡ªğŸ‡¸,ğŸ‡±ğŸ‡°,ğŸ‡§ğŸ‡±,ğŸ‡¸ğŸ‡­,ğŸ‡°ğŸ‡³,ğŸ‡±ğŸ‡¨,ğŸ‡µğŸ‡²,ğŸ‡»ğŸ‡¨,ğŸ‡¸ğŸ‡©,ğŸ‡¸ğŸ‡·,ğŸ‡¸ğŸ‡¿,ğŸ‡¸ğŸ‡ª,ğŸ‡¨ğŸ‡­,ğŸ‡¸ğŸ‡¾,ğŸ‡¹ğŸ‡¼,ğŸ‡¹ğŸ‡¯,ğŸ‡¹ğŸ‡¿,ğŸ‡¹ğŸ‡­,ğŸ‡¹ğŸ‡±,ğŸ‡¹ğŸ‡¬,ğŸ‡¹ğŸ‡°,ğŸ‡¹ğŸ‡´,ğŸ‡¹ğŸ‡¹,ğŸ‡¹ğŸ‡³,ğŸ‡¹ğŸ‡·,ğŸ‡¹ğŸ‡²,ğŸ‡¹ğŸ‡¨,ğŸ‡¹ğŸ‡»,ğŸ‡»ğŸ‡®,ğŸ‡ºğŸ‡¬,ğŸ‡ºğŸ‡¦,ğŸ‡¦ğŸ‡ª,ğŸ‡¬ğŸ‡§,ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿,ğŸ´ó §ó ¢ó ³ó £ó ´ó ¿,ğŸ´ó §ó ¢ó ·ó ¬ó ³ó ¿,ğŸ‡ºğŸ‡³,ğŸ‡ºğŸ‡¸,ğŸ‡ºğŸ‡¾,ğŸ‡ºğŸ‡¿,ğŸ‡»ğŸ‡º,ğŸ‡»ğŸ‡¦,ğŸ‡»ğŸ‡ª,ğŸ‡»ğŸ‡³,ğŸ‡¼ğŸ‡«,ğŸ‡ªğŸ‡­,ğŸ‡¾ğŸ‡ª,ğŸ‡¿ğŸ‡²,ğŸ‡¿ğŸ‡¼
    ]
    width: 200

  grid:
    classname: 'flex flex-wrap'
    columns: 12
    patterns:
      '4|4|4': 'md:w-1/3|md:w-1/3|md:w-1/3'
      '4|8': 'md:w-1/3|md:w-2/3'
      '6|6': 'md:w-1/2|md:w-1/2'
      '8|4': 'md:w-2/3|md:w-1/3'

  text:
    classname: 'text-arx'
    
  align:
    'left': 'text-left'
    'center': 'text-center'
    'right': 'text-right'
    'justify': 'text-justify'

  format: ['div', 'h1', 'h2', 'h3', 'ul', 'ol']

  image:
    thumbnail: 1000Ã—1000Ã—max

  imageposition:
      items:
          left: 'float-left'
          center: false
          right: 'float-right'

  codemirror:
    lineNumbers: true

  editor:
    markup: text
    grammarly: true
    minHeight: '600px'
    add: 'bottom'

  addbarAdd: ['text']
  addbarHide: ['paragraph']


plugins:
  ~
